apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmChartInflationGenerator:
- chartName: harbor
  chartVersion: 1.5.2
  chartRepoUrl: https://helm.goharbor.io
  values: values.yaml
  releaseName: harbor
  # releaseNamespace: solar-system
